site_name: 'Elementos de Sistemas'
theme:
  name: active-handout-theme

docs_dir: 'docs-src'
site_url: https://insper.github.io/Z01.1/
edit_uri: 'edit/docs/docs-src/'
repo_name: 'Insper/Z01.1'
repo_url: 'https://github.com/insper/Z01.1'
copyright: 'Copyright &copy; Rafael Corsi @ insper'

google_analytics:
  - UA-G-XQ38NZ62XF
  - auto

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - active-handout:
      telemetry: true
      backend_url: https://devlife-api.insper-comp.com.br/
      course_slug: 25b-ele
  - glightbox
  - termynal

extra:
  custom_variables:
    lab2_link: ''
    form_scrum_link: 'https://forms.gle/N39CPVszb47G1QP18'
    form_dev_link: 'https://forms.gle/dLycYTxD3mgAuDQU9'
    apsA_date: 'Sexta  - 29/08'
    apsB_date: 'Quarta  - 10/09'
    apsC_date: 'Quarta  - 17/09'
    apsD_date: 'Sexta - 26/09'
    apsE_date: 'Quarta - 15/10'
    apsF_date: 'Sexta - 24/10'
    apsG_date: 'Quarta - 05/11'
    apsI_date: 'Sexta - 14/11'
    apsMR_date: 'Sexta - 30/05'

markdown_extensions:
  - markdown.extensions.admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.critic:
      mode: view
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true


nav:
- Home: 'index.md'
- Avaliação: 'Home/Avaliacoes-Informacoes.md'
- Aulas:
  - Agosto:
    - '13/08 - Organização': 
      - Slides: 'https://github.com/Insper/Z01.1/blob/main/Aulas/01-OrganizacaoDeComputadores.pdf'
    - '15/08 - Dados digitais':
      - 'Leitura Prévia': 'commum-content/teoria/Teoria-Dados.md'
      - 'Exercícios 1': 'https://github.com/Insper/Z01.1/blob/main/Exercicios/Dados_1.pdf'
      #- 'Exercícios 1 - solução': 'https://github.com/Insper/Z01.1/blob/main/Exercicios/Dados_1_respostas.pdf'
      - 'Exercícios 2': 'Exercicios/Exercicio-Dados-2.md'
      #- 'Exercícios 1 - solução': 'https://github.com/Insper/Z01.1/blob/main/Exercicios/Exercicio-Dados-2_resolucao.pdf'
    - '20/08 - Aritmética':
      - 'Leitura Prévia': 'commum-content/teoria/Teoria-Aritmetica-Binaria.md'
      - 'Exercícios 1':  'https://github.com/Insper/Z01.1/blob/master/Exercicios/Exercicio-Aritmetica-Booleana.pdf'
      #- 'Exercícios 1 - solução': 'https://github.com/Insper/Z01.1/blob/master/Exercicios/Exercicio-Aritmetica-Booleana_resolvido.pdf'
    - '22/08 - Álgebra':
      - 'Leitura Prévia': 'Teoria/Teoria-Algebra-Booleana.md'
      - 'Exercícios 1': 'Exercicios/Exercicio-Algebra-Booleana-1.md'
      - 'Exercícios 2': 'Exercicios/Exercicio-Algebra-Booleana-2.md'  
      - 'APS-A - Início': 'Projetos/A-Algebra-CIs.md'
    - '27/08 - Transistores':
      - 'Leitura Prévia - 1': 'commum-content/teoria/Teoria-CMOS.md'
      - 'Leitura Prévia - 2': 'commum-content/teoria/Teoria-RTL.md'
      - 'Lab 1': 'Labs/Lab1-A-Transistores-CI.md'
      - 'APS-A': 'Projetos/A-Algebra-CIs.md'
  - Setembro:
    - '03/09 - VHDL':
      - 'Leitura Prévia - VHDL': 'VHDL/VHDL-basico.md'
      - 'VHDL Combinacional': 'VHDL/VHDL-Combinacional.md'
      - 'VHDL Port Map': 'VHDL/VHDL-port-map.md'
      - 'Lab 2': 'Labs/Lab3-LogiComb-FPGA.md'
    - '05/09 - Componentes digitais':
      - 'Leitura Prévia': 'commum-content/teoria/Teoria-Componentes.md'
      - 'Lab 3': 'Labs/Lab4-LogiComb.md'
      - 'APS-B': 'Projetos/B-LogiComb.md'
    - '10/09 - Formas de ondas': 
      - 'Lab 4': 'Labs/Lab6-Waves.md'
      - 'APS-B': 'Projetos/B-LogiComb.md'
    - '12/09 - Aritmética HW': 
      - 'Leitura Prévia': 'commum-content/teoria/Teoria-Aritmetica-Binaria-HW.md'
      - 'Lab 5': 'Labs/Lab5-Adder.md'
      - 'APS-C': 'Projetos/C-ula.md'
    - '17/09 - ULA': 
      - 'Leitura Prévia': 'commum-content/teoria/Teoria-ULA.md'
      - 'Lab 6': 'Labs/Lab7-ULA.md'
      - 'Simulador ULA': 'https://renan-tr.github.io/simulador/ula'  
      - 'APS-C': 'Projetos/C-ula.md'
    - '19/09 - Lógica Sequencial': 
      - 'Leitura Prévia': 'Teoria/Teoria-Logica-Sequencial.md'
      - 'VHDL Sequencial': 'VHDL/VHDL-Sequencial.md'
      #- 'Exercícios': 'https://forms.gle/XMsFCDMYsmz1qUP86'
      #- 'Exercícios - solução': : 'https://github.com/Insper/Z01.1/blob/master/Exercicios/Lógica-Sequencial_resolucao.pdf'
      - 'Lab 7': 'Labs/Lab8-Seq.md'
      - 'APS-D': 'Projetos/D-LogSeq.md'
    - '24/09 - Componentes sequenciais': 
      - 'Leitura Prévia': 'commum-content/teoria/Teoria-Sequencial-Componentes.md'
      - 'APS-D': 'Projetos/D-LogSeq.md'
  - Outubro:
    - '08/10 - Linguagem de Máquina': 
      - 'Leitura Prévia': 'commum-content/teoria/Teoria-Linguagem-de-Maquina.md'
      - 'Instruction Set': "commum-content/z01/z01-InstructionSet.md"
    - '10/10 - CPU': 
      - 'Leitura Prévia': 'commum-content/teoria/Teoria-Z01.md'
      - 'Exercícios 1': 'Exercicios/Exercicio-CPU-1.md'
      - 'Exercícios 2': 'Exercicios/Exercicio-CPU-2.md'
      - 'Lab 8': 'Labs/Lab10-CPU.md'
      - 'APS-E': 'Projetos/E-CPU.md'
    - 15/10: 
      - 'Programando na FPGA': 'Labs/Lab10.2-CPU-FPGA.md'
      - 'APS-E': 'Projetos/E-CPU.md'
    - '17/10 - Assembly': 
      - 'Leitura Prévia': 'Teoria/Teoria-Assembly.md'
      - 'Resumo Assembly': 'commum-content/z01/z01-Resumo-Assembly.md'
      - 'Assembly Online Simulator': 'https://renan-tr.github.io/simulador/assembly'
    - '22/10 - Assembly Saltos': 
      - 'Leitura Prévia - memória': 'commum-content/teoria/Teoria-Z01-mapadeMemoria.md'
      - 'Leitura Prévia - saltos': 'commum-content/teoria/Teoria-nasm-jump.md'
      - 'Lab 9': 'Labs/Lab12-Assembly.md'
      - 'Lab 10': 'Labs/Lab13-Assembly.md'
      - 'APS-F': 'Projetos/F-Assembly.md'
    - 24/10: 
      - 'Leitura Prévia - memória': 'commum-content/teoria/Teoria-Z01-mapadeMemoria.md'
      - 'Leitura Prévia - saltos': 'commum-content/teoria/Teoria-nasm-jump.md'
      - 'Lab 11': 'Labs/Lab14-Assembly.md'
      - 'Lab 12': 'Labs/Lab15-Assembly-FPGA.md'
      - 'APS-F': 'Projetos/F-Assembly.md'
    - '29/10 - Assembler': 
      - 'Leitura Prévia': 'commum-content/teoria/Teoria-Assembler.md'
      - 'Leitura Prévia': 'commum-content/teoria/Teoria-Assembler-SymbolTable.md'
    - 31/10: 
      - 'Lab 13 - Assembler':
        - 'Labs/Lab16.1-Assembler.md'
        - 'Labs/Lab16.2-Assembler.md'
        - 'Labs/Lab16.3-Assembler.md'
        - 'Labs/Lab16.4-Assembler.md'
        - 'Labs/Lab16.5-Assembler.md'
        - 'Labs/Lab16.6-Assembler.md'
      - 'APS-G': 'Projetos/G-Assembler.md'
  - Novembro:
    - 05/11: 
      - 'APS-G': 'Projetos/G-Assembler.md'
    - '07/11 - VM': 
      - 'Leitura Prévia': 'commum-content/teoria/Teoria-vm.md'
      - 'Leitura Prévia': 'commum-content/teoria/Teoria-vm-segmentos.md'
      - 'Leitura Prévia': 'commum-content/teoria/Teoria-vm-memoria.md'  
      - 'Resumo VM': 'commum-content/z01/z01-Resumo-VM.md'
      - 'VM Online Simulator': 'https://renan-tr.github.io/simulador/vm'
    - '12/11 - VMtranslator':
      - 'Lab 14 - VMtranslator':
        - 'Labs/Lab14.1-VMtranslator.md'
        - 'Labs/Lab14.2-VMtranslator.md'    
      - 'APS-H': 'Projetos/I-VMtranslator.md'
    - '14/11 - VM Translator': 
      - 'Leitura Prévia': 'commum-content/teoria/Teoria-vm-jump.md'
      - 'Leitura Prévia': 'commum-content/teoria/Teoria-vm-funcoes.md'
      - 'Leitura Prévia': 'Teoria/VMtranslator-memoria.md'   
      - 'Lab 15': 'Labs/Lab15-VM.md'   
      - 'APS-H': 'Projetos/I-VMtranslator.md'
- Útil:
  - 'Dicas git': 'Util/Util-Dicas-GIT.md'
  - 'Novo projeto (a partir da APS-C)': "Util/Util-Comecando-novo-projeto.md"
#- 'APS-Extra': 'Projetos/X-MR.md'

# - 'Projetos':
#   - 'Projetos/X-MR.md'

# - Labs:
#   - 'Lab 2: Github':
#     - 'Labs/Lab2.1-Ambiente.md'
#     - 'Labs/Lab2.2-Ambiente.md' 
#   # 'Labs/Lab9-PequenaCPU.md'
#   - 'Labs/Lab11-Assembly.md'

# - 'Teoria':
#   #- 'commum-content/teoria/Teoria-Logica-Sequencial.md'
#   #- "commum-content/teoria/Teoria-Assembly.md"
#   - 'Vídeo Aulas (Luciano)': 'Util/Util-Video-Aulas.md'

# - 'VHDL':
#   - 'VHDL/VHDL-RTL.md'
#   - 'VHDL/VHDL-exemplos.md'

# - 'Z01':
#   - "Z01.1 Cheat Sheet": "commum-content/z01/z01-Cheat-Sheet.md"

# - 'Estudo':
#   - 'Linguagem de Máquina': 'https://github.com/Insper/Z01.1/blob/master/Exercicios/Linguagem_de_maquina.pdf' #'https://forms.gle/6jNZR4CAELJ69ZjXA'
#   - 'Linguagem de Máquina - respostas': 'https://github.com/Insper/Z01.1/blob/main/Exercicios/Extras/Linguagem_de_maquina_respostas.pdf' 

# - Útil:
# #  - "commum-content/util/Util-Comecando-novo-projeto.md"
#   - "Util/Util-Comecando-novo-projeto.md"
# #  - "commum-content/util/Util-vixi-sou-scrum.md"
#   - "Util/Util-vixi-sou-scrum.md"
# #  - 'Dicas git': 'Util/Util-Dicas-GIT.md'

# - História:
#   - 'Util/Historia-linux.md'


