site_name: 'Elementos de Sistemas'
theme:
  name: active-handout-theme

docs_dir: 'docs-src'
site_url: https://insper.github.io/Z01.1/
edit_uri: 'edit/docs/docs-src/'
repo_name: 'Insper/Z01.1'
repo_url: 'https://github.com/insper/Z01.1'
copyright: 'Copyright &copy; Rafael Corsi @ insper'

google_analytics:
  - UA-G-XQ38NZ62XF
  - auto

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - active-handout:
      telemetry: true
      backend_url: https://devlife-api.insper-comp.com.br/
      course_slug: 23b-ele
  - glightbox
  - termynal

markdown_extensions:
  - markdown.extensions.admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.critic:
      mode: view
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true


nav:
- Home:
  - 'index.md'
  - 'Sobre-Criterios-de-Avaliacao.md'
  - 'Sobre-Rubricas.md'

- 'Util-Aulas.md'
- '21a/Avaliacoes.md'

- 'Projetos':
  - 'A-Ambiente-Desenvolvimento-Projeto.md'
  - 'LogiComb-Projeto.md'
  - 'ula-Projeto.md'
  #- 'ula-Projeto-dicas.md'
  - 'seq-Projeto.md'
  - 'assembly-Projeto.md'
  - 'F - CPU':
      - 'cpu-Projeto.md'
      - 'cpu-Testando.md'
  - 'assembler-Projeto.md'
  - 'vm-Projeto.md'
  - 'J-VMtranslator-Projeto.md'
  - 'X-Processadores-Projeto.md'

- Labs:
  - 'A-Transistores-Lab-1-22.md'
  - 'A-Ambiente-Lab-1.md'
  - 'A-Ambiente-Lab-2.md'
#  - 'A-Transistores-Lab-1.md'
  - 'LogiComb-Lab-1.md'
  - 'LogiComb-Lab-2.md'
  - 'ula-Lab-1.md'
  - 'ula-Lab-2.md'
  - 'ula-Lab-3.md'  
  - 'seq-Lab-1.md'
  - 'assembly-Lab-1.md'
  - 'assembly-Lab-2.md'
  - 'assembly-Lab-3.md'
  - 'assembly-Lab-4.md'
  - 'assembly-lab-HW.md'
  - 'ula-lab-4.md'
  - 'cpu-lab-1.md'
  - 'Lab 16: Assembler':
    - 'assembler-Lab-1.md'
    - 'assembler-Lab-1-parte-1.md'
    - 'assembler-Lab-1-parte-2.md'
    - 'assembler-Lab-1-parte-3.md'
    - 'assembler-Lab-1-parte-4.md'
    - 'assembler-Lab-1-parte-5.md'
  - 'vm-Lab-1.md'
  - 'Lab 18: VMtranslator':
    - 'VMtranslator-Lab-1-old.md'
    - 'VMtranslator-Lab-1.md'

- 'Teoria':
  - 'commum-content/teoria/Teoria-Dados.md'
  - 'commum-content/teoria/Teoria-Algebra-Booleana.md'
  - 'commum-content/teoria/Teoria-CMOS.md'
  - 'commum-content/teoria/Teoria-RTL.md'
  - 'commum-content/teoria/Teoria-Componentes.md'
  - 'commum-content/teoria/Teoria-Aritmetica-Binaria.md'
  - 'commum-content/teoria/Teoria-Aritmetica-Binaria-HW.md'
  - 'commum-content/teoria/Teoria-ULA.md'
  - 'commum-content/teoria/Teoria-Logica-Sequencial.md'
  - 'commum-content/teoria/Teoria-Sequencial-Componentes.md'
  - 'commum-content/teoria/Teoria-Z01.md'
  - 'commum-content/teoria/Teoria-Assembly.md'
  - 'commum-content/teoria/Teoria-Z01-mapadeMemoria.md'
  - 'commum-content/teoria/Teoria-nasm-jump.md'
  - 'commum-content/teoria/Teoria-Linguagem-de-Maquina.md'
  - 'commum-content/teoria/Teoria-Assembler.md'
  - 'commum-content/teoria/Teoria-Assembler-SymbolTable.md'
  - 'commum-content/teoria/Teoria-vm.md'
  - 'commum-content/teoria/Teoria-vm-segmentos.md'
  - 'commum-content/teoria/Teoria-vm-jump.md'
  - 'commum-content/teoria/Teoria-vm-funcoes.md'
  - 'commum-content/teoria/Teoria-vm-memoria.md'
  - 'commum-content/teoria/Vídeo Aulas (Luciano)': 'Util-Video-Aulas.md'

- 'VHDL':
  - 'VHDL-basico.md'
  - 'VHDL-Combinacional.md'
  - 'VHDL-port-map.md'
  - 'VHDL-Sequencial.md'
  - 'VHDL-RTL.md'
  - 'VHDL-exemplos.md'

- 'Z01':
  - "Resumo Assembly": "commum-content/z01/z01-Resumo-Assembly.md"
  - "Z01.1 Cheat Sheet": "commum-content/z01/z01-Cheat-Sheet.md"
  - "Instruction Set": "commum-content/z01/z01-InstructionSet.md"
  - "Resumo VM": "commum-content/z01/z01-Resumo-VM.md"

- 'Estudo':
  - 'Dados Digitais - 1': 'https://docs.google.com/spreadsheets/d/1rN_zQqYaVI8PjAhKqEBCmY-_06I0X9dD0RddcI-miJs/edit?usp=sharing'
  - 'Dados Digitais - 1 - pdf': 'https://github.com/Insper/Z01.1/blob/main/Exercicios/Dados_1.pdf'
  - 'Dados Digitais - 1 - respostas': 'https://github.com/Insper/Z01.1/blob/main/Exercicios/Dados_1_respostas.pdf'
  - 'Exercicio-Dados-2.md'
  - 'Dados Digitais - 2 - respostas': 'https://github.com/Insper/Z01.1/blob/main/Exercicios/Exercicio-Dados-2_resolucao.pdf'
  - 'Exercicio-Algebra-Booleana-1.md'
  - 'Exercicio-Algebra-Booleana-2.md'  
  - 'Handout Aritmetica Booleana': 'https://github.com/Insper/Z01.1/blob/master/Exercicios/Exercicio-Aritmetica-Booleana.pdf'
#  - 'Handout Aritmetica Booleana - Resolução': 'https://github.com/Insper/Z01.1/blob/master/Exercicios/Exercicio-Aritmetica-Booleana_resolvido.pdf'
  - 'Lógica Sequencial': 'https://forms.gle/XMsFCDMYsmz1qUP86'
#  - 'Lógica Sequencial - resolução': 'https://github.com/Insper/Z01.1/blob/master/Exercicios/Lógica-Sequencial_resolucao.pdf'
  - 'Linguagem de Máquina': 'https://github.com/Insper/Z01.1/blob/master/Exercicios/Linguagem_de_maquina.pdf' #'https://forms.gle/6jNZR4CAELJ69ZjXA'
#  - 'Linguagem de Máquina - respostas': 'https://github.com/Insper/Z01.1/blob/master/Exercicios/Linguagem_de_maquina_respostas.pdf' 
  - 'Exercicio-CPU-1.md'
  - 'Exercicio-CPU-2.md'

- Útil:
  - "commum-content/util/Util-Comecando-novo-projeto.md"
  - "commum-content/util/Util-vixi-sou-scrum.md"
  - "commum-content/util/Util-vixi-sou-dev.md"
  - 'Dicas git': 'Util-Dicas-GIT.md'

- História:
  - 'Historia-linux.md'

#- Atendimento:
#  - 'Atendimento.md'

