site_name: 'Elementos de Sistemas'
theme:
  name: active-handout
  features:
    - navigation.instant
  palette:
      primary: 'black'
      accent: 'pink'

docs_dir: 'docs-src'

site_url: https://insper.github.io/Z01.1/
edit_uri: 'edit/docs/docs-src/'

repo_name: 'Insper/Z01.1'
repo_url: 'https://github.com/insper/Z01.1'

copyright: 'Copyright &copy; Rafael Corsi @ insper'

google_analytics:
  - UA-G-XQ38NZ62XF
  - auto

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/js-yaml/4.0.0/js-yaml.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/gh/insper-education/active-handout-plugins-js@main/package/plugin-bundle.js

plugins:
  - search
  - git-revision-date-localized
  - active-exercises:
      offering_id: 1

extra:
  ihandout_config:
#    calendar: /active-handout/reference/calendar/calendar.yml
#    counter:
#      - question
#      - tip
#      - exercise
#      - example
    report:
      api-base: https://127.0.0.1:8080/api/offerings/1/
      url: https://127.0.0.1:8080/api/offerings/1/exercises/

markdown_extensions:
  - markdown.extensions.attr_list
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
- Home: 'index.md'

- 'Informações Gerais':
  - 'Home/Sobre-Criterios-de-Avaliacao.md'
  - 'Home/Sobre-Rubricas.md'
  - 'Home/Util-Aulas.md'
  - 'Home/Avaliacoes.md'

- 'Projetos':
  - 'Projetos/A-Algebra-Transistores.md'
  - 'Projetos/B-LogiComb.md'
  - 'Projetos/C-ula.md'
  #- 'Projetos/C-ula-dicas.md'
  - 'Projetos/D-LogSeq.md'
  - 'Projetos/E-CPU.md'
  #    - 'Projetos/E-CPU-Testando.md'
  - 'Projetos/F-Assembly.md'
  - 'Projetos/G-Assembler.md'
  - 'Projetos/H-VM.md'
  #- 'Projetos/I-VMtranslator.md'
  - 'Projetos/X-MR.md'

- Labs:
  - 'Labs/Lab1-A-Transistores.md'
  - 'Lab 2: Github':
    - 'Labs/Lab2.1-Ambiente.md'
    - 'Labs/Lab2.2-Ambiente.md'
  - 'Labs/Lab3-LogiComb-FPGA.md'
  - 'Labs/Lab4-LogiComb.md'
  - 'Labs/Lab5-ULA.md'
  - 'Labs/Lab6-Waves.md'
  - 'Labs/Lab7-ULA.md'  
  - 'Labs/Lab8-Seq.md'
  - 'Labs/Lab9-PequenaCPU.md'
  - 'Labs/Lab10-CPU.md'
  - 'Labs/Lab11-Assembly.md'
  - 'Labs/Lab12-Assembly.md'
  - 'Labs/Lab13-Assembly.md'
  - 'Labs/Lab14-Assembly.md'
  - 'Labs/Lab15-Assembly-FPGA.md'
  - 'Lab 16: Assembler':
    - 'Labs/Lab16.1-Assembler.md'
    - 'Labs/Lab16.2-Assembler.md'
    - 'Labs/Lab16.3-Assembler.md'
    - 'Labs/Lab16.4-Assembler.md'
    - 'Labs/Lab16.5-Assembler.md'
    - 'Labs/Lab16.6-Assembler.md'
  - 'Labs/Lab17-VM.md'
  - 'Lab 18: VMtranslator':
    - 'Labs/Lab18.1-VMtranslator.md'
    - 'Labs/Lab18.2-VMtranslator.md'

- 'Teoria':
  - 'commum-content/teoria/Teoria-Dados.md'
  - 'commum-content/teoria/Teoria-Aritmetica-Binaria.md'
  - 'commum-content/teoria/Teoria-Algebra-Booleana.md'
  - 'Teoria/Teoria-CMOS.md'
  - 'commum-content/teoria/Teoria-RTL.md'
  - 'commum-content/teoria/Teoria-Componentes.md'
  - 'commum-content/teoria/Teoria-Aritmetica-Binaria-HW.md'
  - 'commum-content/teoria/Teoria-ULA.md'
  - 'commum-content/teoria/Teoria-Logica-Sequencial.md'
  - 'commum-content/teoria/Teoria-Sequencial-Componentes.md'
  - 'commum-content/teoria/Teoria-Z01.md'
  - 'Teoria/Teoria-Assembly.md'
  - 'commum-content/teoria/Teoria-Z01-mapadeMemoria.md'
  - 'commum-content/teoria/Teoria-nasm-jump.md'
  - 'commum-content/teoria/Teoria-Linguagem-de-Maquina.md'
  - 'commum-content/teoria/Teoria-Assembler.md'
  - 'Tabelas de Símbolos': 'Teoria/assembler-Dicas-SymbolTable.md'
  - 'commum-content/teoria/Teoria-vm.md'
  - 'commum-content/teoria/Teoria-vm-segmentos.md'
  - 'commum-content/teoria/Teoria-vm-jump.md'
  - 'commum-content/teoria/Teoria-vm-funcoes.md'
  - 'commum-content/teoria/Teoria-vm-memoria.md'
  - 'Teoria/VMtranslator-memoria.md'
  - 'Vídeo Aulas (Luciano)': 'Util/Util-Video-Aulas.md'

- 'VHDL':
  - 'VHDL/VHDL-basico.md'
  - 'VHDL/VHDL-Combinacional.md'
  - 'VHDL/VHDL-port-map.md'
  - 'VHDL/VHDL-Sequencial.md'
  - 'VHDL/VHDL-RTL.md'
  - 'VHDL/VHDL-exemplos.md'

- 'Z01':
  - 'Resumo Assembly': 'Z01/Util-Resumo-Assembly.md'
  - 'Z01.1 Cheat Sheet': 'Z01/Util-Z01.1-Cheat-Sheet.md'
  - 'Instruction Set': 'Z01/Util-InstructionSet.md'
  - 'Resumo VM': 'Z01/Util-Resumo-VM.md'

- 'Estudo':
  - 'Dados Digitais - 1': 'https://docs.google.com/spreadsheets/d/1rN_zQqYaVI8PjAhKqEBCmY-_06I0X9dD0RddcI-miJs/edit?usp=sharing'
  - 'Dados Digitais - 1 - pdf': 'https://github.com/Insper/Z01.1/blob/main/Exercicios/Dados_1.pdf'
  - 'Dados Digitais - 1 - respostas': 'https://github.com/Insper/Z01.1/blob/main/Exercicios/Dados_1_respostas.pdf'
  - 'Exercicios/Exercicio-Dados-2.md'
  - 'Dados Digitais - 2 - respostas': 'https://github.com/Insper/Z01.1/blob/main/Exercicios/Exercicio-Dados-2_resolucao.pdf'
  - 'Exercicios/Exercicio-Algebra-Booleana-1.md'
  - 'Exercicios/Exercicio-Algebra-Booleana-2.md'  
  - 'Handout Aritmetica Booleana': 'https://github.com/Insper/Z01.1/blob/master/Exercicios/Exercicio-Aritmetica-Booleana.pdf'
#  - 'Handout Aritmetica Booleana - Resolução': 'https://github.com/Insper/Z01.1/blob/master/Exercicios/Exercicio-Aritmetica-Booleana_resolvido.pdf'
  - 'Lógica Sequencial': 'https://forms.gle/XMsFCDMYsmz1qUP86'
#  - 'Lógica Sequencial - resolução': 'https://github.com/Insper/Z01.1/blob/master/Exercicios/Lógica-Sequencial_resolucao.pdf'
  - 'Linguagem de Máquina': 'https://github.com/Insper/Z01.1/blob/master/Exercicios/Linguagem_de_maquina.pdf' #'https://forms.gle/6jNZR4CAELJ69ZjXA'
#  - 'Linguagem de Máquina - respostas': 'https://github.com/Insper/Z01.1/blob/master/Exercicios/Linguagem_de_maquina_respostas.pdf' 
  - 'Exercicios/Exercicio-CPU-1.md'
  - 'Exercicios/Exercicio-CPU-2.md'

- Útil:
  - 'Util/Util-Comecando-novo-projeto.md'
  - 'Util/Util-vixi-sou-scrum.md'
#  - 'Dicas git': 'Util/Util-Dicas-GIT.md'
  - 'Util/Util-Dicas-Actions.md'
  - 'Infraestrutura': 'Util/Util-Infraestrutura.md'
  - 'Util/Util-VM-Linux.md'

- História:
  - 'Util/Historia-linux.md'


